language: shell
os: linux
dist: bionic

addons:
  apt:
    packages:
    - ffmpeg
    - python3-pip
    - python3-setuptools

script:
    - python3 -m pip install --upgrade yt-dlp
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_74.mp4 -o Capitulo_74.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_75.mp4 -o Capitulo_75.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_76.mp4 -o Capitulo_76.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_77.mp4 -o Capitulo_77.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_78.mp4 -o Capitulo_78.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_79.mp4 -o Capitulo_79.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_80.mp4 -o Capitulo_80.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_81 -o Capitulo_81.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_82 -o Capitulo_82.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_83 -o Capitulo_83.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_84 -o Capitulo_84.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_85 -o Capitulo_85.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_86 -o Capitulo_86.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_87 -o Capitulo_87.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_88 -o Capitulo_88.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_89.mp4 -o Capitulo_89.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_90.mp4 -o Capitulo_90.mp4

    - curl -T Capitulo_74.mp4 http://transfer.sh
    - curl -T Capitulo_75.mp4 http://transfer.sh
    - curl -T Capitulo_76.mp4 http://transfer.sh
    - curl -T Capitulo_77.mp4 http://transfer.sh
    - curl -T Capitulo_78.mp4 http://transfer.sh
    - curl -T Capitulo_79.mp4 http://transfer.sh
    - curl -T Capitulo_80.mp4 http://transfer.sh
    - curl -T Capitulo_81.mp4 http://transfer.sh
    - curl -T Capitulo_82.mp4 http://transfer.sh
    - curl -T Capitulo_83.mp4 http://transfer.sh
    - curl -T Capitulo_84.mp4 http://transfer.sh
    - curl -T Capitulo_85.mp4 http://transfer.sh
    - curl -T Capitulo_86.mp4 http://transfer.sh
    - curl -T Capitulo_87.mp4 http://transfer.sh
    - curl -T Capitulo_88.mp4 http://transfer.sh
    - curl -T Capitulo_89.mp4 http://transfer.sh
    - curl -T Capitulo_90.mp4 http://transfer.sh
