language: shell
os: linux
dist: focal

addons:
  apt:
    packages:
    - ffmpeg
    - python3-setuptools

script:
    - python3 -m pip install --upgrade yt-dlp
    - yt-dlp -o 'Capitulo_128.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-128/4351392
    - yt-dlp -o 'Capitulo_129.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-129/4360074
    - yt-dlp -o 'Capitulo_130.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-130/4360075
    - yt-dlp -o 'Capitulo_131.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-131/4360076
    - yt-dlp -o 'Capitulo_132.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-132/4360077
    - yt-dlp -o 'Capitulo_133.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-133/4360078
    - yt-dlp -o 'Capitulo_134.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-134/4360079
    - yt-dlp -o 'Capitulo_135.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-135/4360080
    - yt-dlp -o 'Capitulo_136.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-136/4360081
    - yt-dlp -o 'Capitulo_137.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-137/4360082
    - yt-dlp -o 'Capitulo_138.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-138/4360083
    - yt-dlp -o 'Capitulo_139.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-139/4360084
    - curl -T Capitulo_128.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_128.mp4
    - curl -T Capitulo_129.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_129.mp4
    - curl -T Capitulo_130.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_130.mp4
    - curl -T Capitulo_131.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_131.mp4
    - curl -T Capitulo_132.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_132.mp4
    - curl -T Capitulo_133.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_133.mp4
    - curl -T Capitulo_134.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_134.mp4
    - curl -T Capitulo_135.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_135.mp4
    - curl -T Capitulo_136.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_136.mp4
    - curl -T Capitulo_137.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_137.mp4
    - curl -T Capitulo_138.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_138.mp4
    - curl -T Capitulo_139.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_139.mp4



#    - yt-dlp -o 'Capitulo_XX.%(ext)s' URL
  
