language: shell
os: linux
dist: focal

addons:
  apt:
    packages:
    - ffmpeg
    - python3-setuptools

script:
    - pip3 install --upgrade youtube-dl
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_11%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-11/4264196	
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_12%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-12/4270797	
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_13%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-13/4270798	
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_14%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-14/4270799	
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_15%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-15/4270800	
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_16%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-16/4270801	
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_17%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-17/4270802	
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_18%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-18/4270803	
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_19%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-19/4270804	
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_20%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-20/4270805	
    - curl -T ./Capitulo_11.mp4 http://transfer.sh
    - curl -T ./Capitulo_12.mp4 http://transfer.sh
    - curl -T ./Capitulo_13.mp4 http://transfer.sh
    - curl -T ./Capitulo_14.mp4 http://transfer.sh
    - curl -T ./Capitulo_15.mp4 http://transfer.sh
    - curl -T ./Capitulo_16.mp4 http://transfer.sh
    - curl -T ./Capitulo_17.mp4 http://transfer.sh
    - curl -T ./Capitulo_18.mp4 http://transfer.sh
    - curl -T ./Capitulo_19.mp4 http://transfer.sh
    - curl -T ./Capitulo_20.mp4 http://transfer.sh

