language: shell
os: linux
dist: focal

addons:
  apt:
    packages:
    - ffmpeg
    - python3-setuptools

script:
    - yt-dlp -o 'Capitulo_116.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-116/4343323
    - yt-dlp -o 'Capitulo_117.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-117/4343325
    - yt-dlp -o 'Capitulo_118.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-118/4343327
    - yt-dlp -o 'Capitulo_119.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-119/4351383
    - yt-dlp -o 'Capitulo_120.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-120/4351384
    - yt-dlp -o 'Capitulo_121.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-121/4351385
    - yt-dlp -o 'Capitulo_122.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-122/4351386
    - yt-dlp -o 'Capitulo_123.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-123/4351387
    - yt-dlp -o 'Capitulo_124.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-124/4351388
    - yt-dlp -o 'Capitulo_125.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-125/4351389
    - yt-dlp -o 'Capitulo_126.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-126/4351390
    - yt-dlp -o 'Capitulo_127.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-127/4351391
    - curl -T Capitulo_116.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_116
    - curl -T Capitulo_117.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_117
    - curl -T Capitulo_118.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_118
    - curl -T Capitulo_119.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_119
    - curl -T Capitulo_120.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_120
    - curl -T Capitulo_121.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_121
    - curl -T Capitulo_122.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_122
    - curl -T Capitulo_123.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_123
    - curl -T Capitulo_124.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_124
    - curl -T Capitulo_125.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_125
    - curl -T Capitulo_126.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_126
    - curl -T Capitulo_127.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_127



#    - yt-dlp -o 'Capitulo_XX.%(ext)s' URL
  
