language: shell
os: linux
dist: bionic

addons:
  apt:
    packages:
    - libc-ares2
    - libcrypto++6
    - mediainfo
    - libmediainfo0v5
    - libzen0v5
    - ffmpeg
    - python3-pip
    - python3-setuptools

script:
    - python3 -m pip install --upgrade yt-dlp

    - wget http://transfer.sh/1qeVJPz/cookies.txt
    - yt-dlp --cookies cookies.txt -o 'El_mayor_regalo.mp4' https://www.infinitomasuno.org/visionado/streaming-mayor-regalo-espanol-2/
    - curl -T El_mayor_regalo.mp4 http://transfer.sh
#    - yt-dlp -o 'Capitulo_XX.%(ext)s' URL
