language: shell
os: linux
dist: bionic

addons:
  apt:
    packages:
    - libc-ares2
    - libcrypto++6
    - mediainfo
    - libmediainfo0v5
    - libzen0v5
    - ffmpeg
    - python3-pip
    - python3-setuptools

script:
    - python3 -m pip install --upgrade yt-dlp
    - wget http://transfer.sh/1QMFl17/megacmd.deb
    - sudo dpkg -i megacmd.deb
    - mega-login $email $pass
    - yt-dlp -o 'Capitulo_119.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-119/4351383
    - mega-put Capitulo_119.mp4 /Y581F-UNIVISION/
    - yt-dlp -o 'Capitulo_120.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-120/4351384
    - mega-put Capitulo_120.mp4 /Y581F-UNIVISION/
    - yt-dlp -o 'Capitulo_120.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-120/4351384
    - mega-put Capitulo_120.mp4 /Y581F-UNIVISION/
    - yt-dlp -o 'Capitulo_121.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-121/4351385
    - mega-put Capitulo_121.mp4 /Y581F-UNIVISION/
    - yt-dlp -o 'Capitulo_122.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-122/4351386
    - mega-put Capitulo_122.mp4 /Y581F-UNIVISION/
    - yt-dlp -o 'Capitulo_123.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-123/4351387
    - mega-put Capitulo_123.mp4 /Y581F-UNIVISION/
    - yt-dlp -o 'Capitulo_124.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-124/4351388
    - mega-put Capitulo_124.mp4 /Y581F-UNIVISION/
    - yt-dlp -o 'Capitulo_125.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-125/4351389
    - mega-put Capitulo_125.mp4 /Y581F-UNIVISION/
#    - yt-dlp -o 'Capitulo_XX.%(ext)s' URL
