language: shell
os: linux
dist: bionic

addons:
  apt:
    packages:
    - ffmpeg
    - python3-pip
    - python3-setuptools

script:
    - python3 -m pip install --upgrade yt-dlp
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_75.mp4 -o Capitulo_75.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_76.mp4 -o Capitulo_76.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_77.mp4 -o Capitulo_77.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_78.mp4 -o Capitulo_78.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_79.mp4 -o Capitulo_79.mp4
    - curl -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_80.mp4 -o Capitulo_80.mp4
    - curl -T Capitulo_75.mp4 http://transfer.sh
    - curl -T Capitulo_76.mp4 http://transfer.sh
    - curl -T Capitulo_77.mp4 http://transfer.sh
    - curl -T Capitulo_78.mp4 http://transfer.sh
    - curl -T Capitulo_79.mp4 http://transfer.sh
    - curl -T Capitulo_80.mp4 http://transfer.sh
