language: shell
os: linux
dist: bionic

addons:
  apt:
    packages:
    - libc-ares2
    - libcrypto++6
    - mediainfo
    - libmediainfo0v5
    - libzen0v5
    - ffmpeg
    - python3-pip
    - python3-setuptools

script:
    - wget -O "El_mayor_regalo.mp4" https://vod-progressive.akamaized.net/exp=1626324755~acl=%2A%2F1304635058.mp4%2A~hmac=99dc1303dc91231a92b0c8e8629a880e85ae6f573fb92e24fd5020434f20e4e7/vimeo-prod-skyfire-std-us/01/1090/13/330451760/1304635058.mp4
    - curl -T El_mayor_regalo.mp4 http://transfer.sh
#    - yt-dlp -o 'Capitulo_XX.%(ext)s' URL
