language: shell
os: linux
dist: focal

addons:
  apt:
    packages:
    - ffmpeg
    - python3-setuptools

script:
    - pip3 install --upgrade youtube-dl
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_31.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-31/4278931
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_32.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-32/4278932
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_33.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-33/4278933
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_34.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-34/4278934
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_35.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-35/4287201
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_36.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-36/4287202
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_37.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-37/4287203
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_38.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-38/4287204
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_39.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-39/4287205
    - curl -T ./Capitulo_31.mp4 http://transfer.sh
    - curl -T ./Capitulo_32.mp4 http://transfer.sh
    - curl -T ./Capitulo_33.mp4 http://transfer.sh
    - curl -T ./Capitulo_34.mp4 http://transfer.sh
    - curl -T ./Capitulo_35.mp4 http://transfer.sh
    - curl -T ./Capitulo_36.mp4 http://transfer.sh
    - curl -T ./Capitulo_37.mp4 http://transfer.sh
    - curl -T ./Capitulo_38.mp4 http://transfer.sh
    - curl -T ./Capitulo_39.mp4 http://transfer.sh
    