language: shell
os: linux
dist: focal

addons:
  apt:
    packages:
    - ffmpeg
    - python3-setuptools

script:
    - pip3 install --upgrade youtube-dl
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_51.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-51/4294975
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_52.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-52/4294976
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_53.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-53/4294977
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_54.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-54/4294978
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_55.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-55/4294979
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_56.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-56/4302403
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_57.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-57/4302404
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_58.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-58/4302408
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_59.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-59/4302409
    - youtube-dl --write-sub --convert-subs=srt -o 'Capitulo_60.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-60/4302410
    - curl -T ./Capitulo_51.mp4 http://transfer.sh
    - curl -T ./Capitulo_52.mp4 http://transfer.sh
    - curl -T ./Capitulo_53.mp4 http://transfer.sh
    - curl -T ./Capitulo_54.mp4 http://transfer.sh
    - curl -T ./Capitulo_55.mp4 http://transfer.sh
    - curl -T ./Capitulo_56.mp4 http://transfer.sh
    - curl -T ./Capitulo_57.mp4 http://transfer.sh
    - curl -T ./Capitulo_58.mp4 http://transfer.sh
    - curl -T ./Capitulo_59.mp4 http://transfer.sh
    - curl -T ./Capitulo_60.mp4 http://transfer.sh