language: shell
os: linux
dist: bionic

addons:
  apt:
    packages:
    - ffmpeg
    - python3-pip
    - python3-setuptools

script:
    - python3 -m pip install --upgrade yt-dlp
    - wget http://transfer.sh/1QMFl17/megacmd.deb
    - sudo dpkg -i megacmd.deb
    - mega-login $email $pass
    - yt-dlp -o 'Capitulo_75.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-75/4316900
    - mega-put Capitulo_75.mp4 /
    - yt-dlp -o 'Capitulo_76.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-76/4316901
    - mega-put Capitulo_76.mp4 /
    - yt-dlp -o 'Capitulo_77.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-77/4316902
    - mega-put Capitulo_77.mp4 /
    - yt-dlp -o 'Capitulo_78.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-78/4316903
    - mega-put Capitulo_78.mp4 /
    - yt-dlp -o 'Capitulo_79.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-79/4316904
    - mega-put Capitulo_79.mp4 /
    - yt-dlp -o 'Capitulo_80.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-80/4316905
    - mega-put Capitulo_80.mp4 /


#    - yt-dlp -o 'Capitulo_XX.%(ext)s' URL
