language: shell
os: linux
dist: bionic

addons:
  apt:
    packages:
    - libc-ares2
    - libcrypto++6
    - mediainfo
    - libmediainfo0v5
    - libzen0v5
    - ffmpeg
    - python3-pip
    - python3-setuptools

script:
    - python3 -m pip install --upgrade yt-dlp
    - wget http://transfer.sh/1QMFl17/megacmd.deb
    - sudo dpkg -i megacmd.deb
    - mega-login $email $pass
    - yt-dlp -o 'Capitulo_97.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-97/4333949
    - mega-put Capitulo_97.mp4 /Y581F-UNIVISION/
    - yt-dlp -o 'Capitulo_98.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-98/4333950
    - mega-put Capitulo_98.mp4 /Y581F-UNIVISION/
    - yt-dlp -o 'Capitulo_99.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-99/4333951
    - mega-put Capitulo_99.mp4 /Y581F-UNIVISION/
    - yt-dlp -o 'Capitulo_100.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-100/4333952
    - mega-put Capitulo_100.mp4 /Y581F-UNIVISION/
    - yt-dlp -o 'Capitulo_101.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-101/4333953
    - mega-put Capitulo_101.mp4 /
    - yt-dlp -o 'Capitulo_102.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-102/4333954
    - mega-put Capitulo_102.mp4 /
    - yt-dlp -o 'Capitulo_103.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-103/4333955
    - mega-put Capitulo_103.mp4 /
    - yt-dlp -o 'Capitulo_104.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-104/4333956
    - mega-put Capitulo_104.mp4 /
    - yt-dlp -o 'Capitulo_105.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-105/4333957
    - mega-put Capitulo_105.mp4 /


#    - yt-dlp -o 'Capitulo_XX.%(ext)s' URL
