language: shell
os: linux
dist: focal

addons:
  apt:
    packages:
    - ffmpeg
    - python3-setuptools

script:
    - python3 -m pip install --upgrade yt-dlp
    - yt-dlp -o 'Capitulo_81.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-81/4316906
    - yt-dlp -o 'Capitulo_82.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-82/4316907
    - yt-dlp -o 'Capitulo_83.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-83/4316908
    - yt-dlp -o 'Capitulo_84.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-84/4316909
    - yt-dlp -o 'Capitulo_85.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-85/4325878
    - yt-dlp -o 'Capitulo_86.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-86/4325879
    - yt-dlp -o 'Capitulo_87.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-87/4325880
    - yt-dlp -o 'Capitulo_88.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-88/4325881
    - yt-dlp -o 'Capitulo_89.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-89/4325882
    - yt-dlp -o 'Capitulo_90.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-90/4325883
    - yt-dlp -o 'Capitulo_91.%(ext)s' https://www.nbc.com/yo-soy-betty-la-fea/video/capitulo-91/4325884
    
    - curl -T Capitulo_80.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_80
    - curl -T Capitulo_81.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_81
    - curl -T Capitulo_82.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_82
    - curl -T Capitulo_83.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_83
    - curl -T Capitulo_84.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_84
    - curl -T Capitulo_85.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_85
    - curl -T Capitulo_86.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_86
    - curl -T Capitulo_87.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_87
    - curl -T Capitulo_88.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_88
    - curl -T Capitulo_89.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_89
    - curl -T Capitulo_90.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_90
    - curl -T Capitulo_91.mp4 -u juanliz:C%9Z2p6c6RqD https://fs5.cdnrobot.xyz/webdav/Capitulo_91


#    - yt-dlp -o 'Capitulo_XX.%(ext)s' URL
  
